### ISSUE TITLE
Update Repo pls

### ISSUE THREAD

**Issue by tphatdzai** [shaurya-jain-06/Attendance_Monitoring_System#1]
The current repo I installed has a lot of errors, specifically that Tensorflow 2.10.0 is no longer supported on MacOS. If possible, please give me your email so I can contact you.

**Comment by tphatdzai** [comment]
@shaurya-jain-06

**Comment by shaurya-jain-06** [comment]
hi @tphatdzai 
yes tensorflow-macos versions 2.9 and 2.10 don't work on MacOS
https://github.com/tensorflow/tensorflow/issues/58339
as stated in this issue, AVX compilation of tensorflow is a problem, however tensorflow conda packages dont seem to give an issue. Moreover tensorflow-macos 2.8 shouldnt be a problem
